### ISSUE TITLE
Unused Dependancy on bitauth/libauth

### ISSUE THREAD

**Issue by flashmatt** [thonymg/vue-zo#1]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [X ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
There is a dependancy on [@bitauth/](https://github.com/bitauth/libauth) in the package.json

I've quickly scanned through the code and can't see this being used. Would you accept a pull request to remove this?

**Comment by mreduar** [comment]
That's kind of weird, isn't it?

**Comment by thonymg** [comment]
Yes you are right I will clean these dependencies
