### ISSUE TITLE
Possible to use this with Vuex/Vue3?

### ISSUE THREAD

**Issue by starredev** [thonymg/vue-zo#4]
Could you help how to implement this?

**Comment by starredev** [comment]
I switched up to Pinia but have some issue with gates.

I'm trying to impelement vue-gates from https://github.com/thonymg/vue-zo 

Inject from vue is not giving the instance and throws undefined but when I inject it right in App.vue it works fine

Wondering if someone knows why this happen

```
import { inject } from 'vue'
import { defineStore } from "pinia";

export const useGatesStore = defineStore("api", () => {
  const $zo = inject("$zo");
  
  const setRoles = () => {
    console.log($zo)
  }

  return {
    setRoles
  };
})
```

**Comment by thonymg** [comment]
Hi, 
Try to use the `$zo = inject("$zo");` in `onMounted`. Obviously the store does not have access to the instance of vueJS

```javascript
export const useGatesStore = defineStore("api", () => {

  let $zo: any;

  const setRoles = () => {
    $zo.setRoles("admin");
    console.log($zo.getRoles());
  };

  onMounted(() => {
    $zo = inject("$zo");
  });

  return {
    setRoles,
  };
});

```

**Comment by starredev** [comment]
@thonymg i'm not using typescript

Im receiving the following error
https://codesandbox.io/s/awesome-rain-1ivbci?file=/src/stores/gates.store.js


TypeError
Cannot assign to read only property 'message' of object 'SyntaxError: /src/stores/gates.store.js: Missing semicolon. (5:9)

  3 |
  4 | export const useAPI = defineStore("api", () => {
  5 |   let $zo: ZoTypes;
    |          ^
